#!/usr/local/bin/python

"""
 get version from svn and set it in evoke
 
 usage: set_major_version <folder> <major_version>

"""

from sys import argv
from os import system

try:
  folder=argv[1]
  if folder and not folder.endswith('/'):
    folder+='/'
except:
  folder='../'  
try:
  maj=argv[2]
except:
  maj='1'  

def set_evoke_major_version(ver):
  fn="%sconfig_base.py" % folder
  new=[]
  for line in open(fn):
    if line.startswith('evoke_major_version='):
      new.append("evoke_major_version=%s #%s"  % (ver,line.split('#')[1]))
    else:
      new.append(line)
  d=open(fn,'w')
  d.writelines(new)

set_evoke_major_version(maj)
system('echo major_version set by set_major_version')
system('svn commit %sconfig_base.py -m "major_version set by set_major_version"' % folder)
